gitkraken-client/adding-and-removing.md

Added images in adding and removing

Added images 

---

gitkraken-client/faq.md
gitkraken-client/how-to-install.md
gitkraken-client/interface.md
gitkraken-client/profiles.md

https://devhelpcenter.wpengine.com/gitkraken-client/how-to-install/
https://devhelpcenter.wpengine.com/gitkraken-client/faq/
https://devhelpcenter.wpengine.com/gitkraken-client/interface/
https://devhelpcenter.wpengine.com/gitkraken-client/profiles/

Second pass on some, adding how-to-install

---

gitkraken-client/adding-and-removing.md
gitkraken-client/editing-files.md

https://devhelpcenter.wpengine.com/gitkraken-client/adding-and-removing/
https://devhelpcenter.wpengine.com/gitkraken-client/editing-files/

Added descriptions

---

gitkraken-client/command-palette.md

https://devhelpcenter.wpengine.com/gitkraken-client/command-palette/

Image preview

---

gitkraken-client/about-enterprise.md
gitkraken-client/common-issues.md
gitkraken-client/configure-enterprise.md
gitkraken-client/date-format.md
gitkraken-client/error-logs.md
gitkraken-client/how-to-install-enterprise.md
gitkraken-client/performance-issues.md
gitkraken-client/standalone.md
gitkraken-client/system-requirements.md
gitkraken-client/upgrade-enterprise.md

https://devhelpcenter.wpengine.com/gitkraken-client/upgrade-enterprise/
https://devhelpcenter.wpengine.com/gitkraken-client/configure-enterprise/
https://devhelpcenter.wpengine.com/gitkraken-client/how-to-install-enterprise/#install_enterprise
https://devhelpcenter.wpengine.com/gitkraken-client/system-requirements/
https://devhelpcenter.wpengine.com/gitkraken-client/about-enterprise/
https://devhelpcenter.wpengine.com/gitkraken-client/common-issues/
https://devhelpcenter.wpengine.com/gitkraken-client/performance-issues/
https://devhelpcenter.wpengine.com/gitkraken-client/date-format/
https://devhelpcenter.wpengine.com/gitkraken-client/error-logs/
https://devhelpcenter.wpengine.com/gitkraken-client/standalone/

Auto stash before checking out "gitkraken/main"

---

gitkraken-client/teams.md
gitkraken-client/themes.md

Replaced images path, and replaced descriptor title for themes.md

Themes and Teams pages verified

---

gitkraken-client/activity-logs.md
gitkraken-client/branching-and-merging.md
gitkraken-client/favorites.md
gitkraken-client/squash.md
gitkraken-client/staging.md
gitkraken-client/stashing.md

- https://devhelpcenter.wpengine.com/gitkraken-client/squash/
- https://devhelpcenter.wpengine.com/gitkraken-client/stashing/
- https://devhelpcenter.wpengine.com/gitkraken-client/staging/
- https://devhelpcenter.wpengine.com/gitkraken-client/branching-and-merging/
- https://devhelpcenter.wpengine.com/gitkraken-client/activity-logs/
- https://devhelpcenter.wpengine.com/gitkraken-client/favorites/

Squash, Staging, activity logs, branching/merging, favorites and Stashing updates 

---

gitkraken-client/interactive-rebase.md
gitkraken-client/linking.md
gitkraken-client/project-groups.md

https://devhelpcenter.wpengine.com/gitkraken-client/interactive-rebase/
https://devhelpcenter.wpengine.com/gitkraken-client/linking/
https://devhelpcenter.wpengine.com/gitkraken-client/project-groups/

Interactive Rebase, Deep Linking, Project Groups images fixed

---

gitkraken-client/how-to-install.md
gitkraken-client/integrations.md
gitkraken-client/stand-alone.md

- https://devhelpcenter.wpengine.com/gitkraken-client/how-to-install/
- https://devhelpcenter.wpengine.com/gitkraken-client/stand-alone/
- https://devhelpcenter.wpengine.com/gitkraken-client/integrations/

Formatting and link fixes

---

gitkraken-client/pushing-and-pulling.md

Updated URL directory to correct one that doesn't contain /icons

Fixed broken link

---

gitkraken-client/gitkraken-client-home.md

Update Home page with new support form link

---

gitkraken-client/current.md

Fixed an crash on some Windows machines when opening the preferences menu.

release notes for 8.9.1

---

gitkraken-client/single-sign-on.md

https://gitkraken.atlassian.net/browse/HC-38

HC-38 Add warning in SSO for Okta dashboards (and other login methods)

---

gitkraken-client/current.md
gitkraken-client/interface.md

v8.10 release notes

---

gitkraken-client/configure-self-managed.md
gitkraken-client/how-to-install-self-hosted.md
gitkraken-client/self-hosted.md
gitkraken-client/single-sign-on.md
gitkraken-client/stand-alone.md
gitkraken-client/upgrade-enterprise.md

Specifically
Enterprise Self-hosted = Self-Hosted Server
Enterprise Stand-Alone = Serverless

Renaming enterprise to on-premise (first pass)

---

gitkraken-client/commit-signing-with-gpg.md

Update link to GH on gpg page
https://gitkraken.atlassian.net/browse/HC-36

Change Github link

---

gitkraken-client/insights.md

Small change to add the available integrations for Insights

Add available integrations

---

gitkraken-client/current.md

First PR of the year! Please don't merge until the release goes out.

9.0.1 release notes

---

gitkraken-client/8x.md

https://gitkraken.atlassian.net/browse/HC-51

HC-51 Fix 8.7 release note links

---

gitkraken-client/how-to-install.md

Update linux install instructions to use updated commands
- for .deb use `apt`
- for .rpm use `dnf`
And add note with link for WSL docs

Updated Linux Install Instruction

---

gitkraken-client/insights.md

https://gitkraken.atlassian.net/browse/HC-54
Add note

HC-54 Add note that creating a cloud workspaces will add a webhook

---

gitkraken-client/how-to-install.md
terms-and-conditions.md

also minor fix to how to install page

Adding terms and conditions page

---

gitkraken-client/faq.md
gitkraken-client/windows-subsystem-for-linux.md

Help center updates for flags to start gkc with for common issues
- Added --disable-gpu to general FAQ
- Added --disable-gpu to WSL page
- Added --ignore-certificate-errors to WSL page

add disable hardware acceleration and ignore cert errors help

---

gitkraken-client/current.md

https://gitkraken.atlassian.net/browse/PMM-205

PMM-205 Help Center Release Notes for 9.3 

---

gitkraken-client/terms-and-conditions.md

Adding:
- support period
- end of life (EOL)
- EOL process
for the page: https://help.gitkraken.com/gitkraken-client/terms-and-conditions/

Adding to support T&Cs

---

gitkraken-client/current.md

https://gitkraken.atlassian.net/browse/PMM-222

PMM-222 9.4 Help Center Release Notes [Do not merge]

---

gitkraken-client/current.md

https://gitkraken.atlassian.net/browse/PMM-235
Formatting check still needed

PMM-235 9.5 in-app release notes

---

gitkraken-client/workspaces.md

New functionalities on Workspaces and add Pull Request complexity score
- Add option to share with individual users
- Add Pull Request complexity score based on lines changed, files changed, and commits made.
- Include Pull Request complexity score in the list of information shown for each pull request.
- Add "Pull" action to perform a pull on all selected repositories within a workspace.
Screenshots will be updated directly to WP

9.5 updates on Workspaces

---

gitkraken-client/experimental-features.md

Added the following actions that are part of the Git Executable feature as of 9.5.0:
- remote branch delete
- tag delete (both local and remote)

Add new git executable actions

---

gitkraken-client/authentication.md
gitkraken-client/current.md
gitkraken-client/open-clone-init.md

- Added to /open-clone-init
- Added to /authentication

Adding embed of Clone tutorial video

---

gitkraken-client/how-to-install.md

https://gitkraken.atlassian.net/browse/PMM-245

PMM-245 Update Help Center with Linux tutorial

---

gitkraken-client/workspaces.md

Hey Joey! Can you please merge and update Wordpress?

Add Cloud Workspaces tutorial to Workspaces Help Center page

---

gitkraken-client/workspaces.md

Hey Joey! Can you please merge and update Wordpress?

Add video tutorial to Local Workspace docs

---

gitkraken-client/current.md

https://gitkraken.atlassian.net/browse/PMM-250
Hey y'all! 
Here are the release notes, as they appear in the application. I recommend cross checking with the final GKC release candidate before merging.
Video link included.

[DO NOT MERGE until 7/10/23] PMM-250 9.6 Help Center release notes

---

gitkraken-client/experimental-features.md

Update Git Executable section with features released in 9.6.0

add git executable features released with 9.6.0

---

gitkraken-client/interface.md
gitkraken-client/profiles.md

Added embed links to /interface.md and /profiles.md to give users a tutorial for understanding how they work.

Add videos for Commit Panel and Profiles

---

gitkraken-client/experimental-features.md

Added Git Executable actions in 9.6.1 to the Experimental Features section

Add git executable features for 9.6.1

---

gitkraken-client/current.md

Please check the spacing on the bullets. Do they indent correctly?

9.7 release notes

---

gitkraken-client/experimental-features.md

Updated Git Executable features for 9.7.0 release:
- Signing tags with SSH

Git Executable features for 9.7.0

---

gitkraken-client/current.md

9.8 release notes [Do not merge]

---

gitkraken-client/diff.md
gitkraken-client/experimental-features.md
gitkraken-client/how-to-install.md
gitkraken-client/pushing-and-pulling.md
gitkraken-client/serverless.md
gitkraken-client/terms-and-conditions.md
gitkraken-client/workspaces.md

- https://gitkraken.atlassian.net/browse/HC-95
- https://gitkraken.atlassian.net/browse/HC-85
- https://gitkraken.atlassian.net/browse/HC-62
- https://gitkraken.atlassian.net/browse/HC-68
- https://gitkraken.atlassian.net/browse/HC-27

Help center updates

---

gitkraken-client/trials.md

https://gitkraken.atlassian.net/browse/HC-119

HC-119 Update trials page

---

gitkraken-client/branching-and-merging.md
gitkraken-client/commits.md
gitkraken-client/experimental-features.md
gitkraken-client/integrations.md
gitkraken-client/open-clone-init.md
gitkraken-client/pushing-and-pulling.md
gitkraken-client/workspaces.md

Hey y'all!
I added the onboarding tutorial videos to the corresponding docs pages. Do the videos render okay?

Add new videos to docs pages

---

gitkraken-client/current.md

Please merge if this looks good.

Embed Changelog Breakdown Video in 9.13
